version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      angular:
        patterns:
          - "@angular/*"
          - "ng-packagr"
      test-tooling:
        patterns:
          - "@types/jasmine"
          - "jasmine-core"
          - "karma*"
    ignore:
      - dependency-name: "typescript"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      actions:
        patterns:
          - "*"
